// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  large_list_image: dynamic(() => import("./LargeListImage")),
  nav_link: dynamic(() => import("./NavLink")),
};
