import Head from "next/head";
import Link from "next/link";

const navLink = ['Websites', 'Contact', 'Pins', 'Search']

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Home Page
      </div>

      <nav>
        {navLink.map((link, i) => (
            <Link href={link.toLowerCase()} key={i}>
                {link}
            </Link>
        ))}
      </nav>
    </>
  );
}
